INFO: 2014-Oct-03 13:46:22: Messages will be sent to messages.msg.
INFO: 2014-Oct-03 13:46:22: Simulation box is periodic with size (lx,ly,lz) = (100,100,10).
INFO: 2014-Oct-03 13:46:22: Reading particle coordinates from file: plane.dat
INFO: 2014-Oct-03 13:46:22: Read data for 3183 particles.
INFO: 2014-Oct-03 13:46:22: Generated group 'all' containing all particles.
INFO: 2014-Oct-03 13:46:22: There are 2 distinct particle types in the system.
INFO: 2014-Oct-03 13:46:22: Periodic flag for the system is set to true.
INFO: 2014-Oct-03 13:46:22: Finished reading system coordinates from plane.dat.
INFO: 2014-Oct-03 13:46:22: Created cell list with 3468 cells.
INFO: 2014-Oct-03 13:46:22: Each cell has dimensions (2.9411764705882355,2.9411764705882355,3.3333333333333335).
INFO: 2014-Oct-03 13:46:22: Using cell lists for neighbour list builds.
INFO: 2014-Oct-03 13:46:22: Created neighbour list with cutoff 2.3999999999999999 and padding distance 0.5.
INFO: 2014-Oct-03 13:46:22: Dump type set to velocity
INFO: 2014-Oct-03 13:46:22: Dump will be sent to the file with base name plane_test with extension vel.
INFO: 2014-Oct-03 13:46:22: Dumping will start after 0 time steps.
INFO: 2014-Oct-03 13:46:22: Dump will be produced every 10000 time steps.
INFO: 2014-Oct-03 13:46:22: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2014-Oct-03 13:46:22: Include info header into the dump file.
INFO: 2014-Oct-03 13:46:22: Adding dump to file plane_test.
INFO: 2014-Oct-03 13:46:22: Parameter freq for dump plane_test is set to 10000.
INFO: 2014-Oct-03 13:46:22: Parameter header for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter multi for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter start for dump plane_test is set to 0.
INFO: 2014-Oct-03 13:46:22: Parameter type for dump plane_test is set to velocity.
INFO: 2014-Oct-03 13:46:22: Dump type set to xyz
INFO: 2014-Oct-03 13:46:22: Dump will be sent to the file with base name plane_test with extension xyz.
INFO: 2014-Oct-03 13:46:22: Dumping will start after 0 time steps.
INFO: 2014-Oct-03 13:46:22: Dump will be produced every 10000 time steps.
INFO: 2014-Oct-03 13:46:22: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2014-Oct-03 13:46:22: Include info header into the dump file.
INFO: 2014-Oct-03 13:46:22: Adding dump to file plane_test.
INFO: 2014-Oct-03 13:46:22: Parameter freq for dump plane_test is set to 10000.
INFO: 2014-Oct-03 13:46:22: Parameter header for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter multi for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter start for dump plane_test is set to 0.
INFO: 2014-Oct-03 13:46:22: Parameter type for dump plane_test is set to xyz.
INFO: 2014-Oct-03 13:46:22: Dump type set to dcd
INFO: 2014-Oct-03 13:46:22: Dump will be sent to the file with base name plane_test with extension dcd.
INFO: 2014-Oct-03 13:46:22: Dumping will start after 0 time steps.
INFO: 2014-Oct-03 13:46:22: Dump will be produced every 1000 time steps.
WARNING: 2014-Oct-03 13:46:22: All time steps will be concatenated to a single file.
INFO: 2014-Oct-03 13:46:22: Adding dump to file plane_test.
INFO: 2014-Oct-03 13:46:22: Parameter freq for dump plane_test is set to 1000.
INFO: 2014-Oct-03 13:46:22: Parameter start for dump plane_test is set to 0.
INFO: 2014-Oct-03 13:46:22: Parameter type for dump plane_test is set to dcd.
INFO: 2014-Oct-03 13:46:22: Dump type set to xyzv
INFO: 2014-Oct-03 13:46:22: Dump will be sent to the file with base name plane_test_dir with extension xyzv.
INFO: 2014-Oct-03 13:46:22: Dumping will start after 0 time steps.
INFO: 2014-Oct-03 13:46:22: Dump will be produced every 1000 time steps.
WARNING: 2014-Oct-03 13:46:22: All time steps will be concatenated to a single file.
INFO: 2014-Oct-03 13:46:22: Include info header into the dump file.
INFO: 2014-Oct-03 13:46:22: Adding dump to file plane_test_dir.
INFO: 2014-Oct-03 13:46:22: Parameter freq for dump plane_test_dir is set to 1000.
INFO: 2014-Oct-03 13:46:22: Parameter header for dump plane_test_dir is set to .
INFO: 2014-Oct-03 13:46:22: Parameter scale for dump plane_test_dir is set to 0.25.
INFO: 2014-Oct-03 13:46:22: Parameter start for dump plane_test_dir is set to 0.
INFO: 2014-Oct-03 13:46:22: Parameter type for dump plane_test_dir is set to xyzv.
INFO: 2014-Oct-03 13:46:22: Dump type set to xyzv
INFO: 2014-Oct-03 13:46:22: Dump will be sent to the file with base name plane_test_vel with extension xyzv.
INFO: 2014-Oct-03 13:46:22: Dumping will start after 0 time steps.
INFO: 2014-Oct-03 13:46:22: Dump will be produced every 1000 time steps.
WARNING: 2014-Oct-03 13:46:22: All time steps will be concatenated to a single file.
INFO: 2014-Oct-03 13:46:22: Include info header into the dump file.
INFO: 2014-Oct-03 13:46:22: Adding dump to file plane_test_vel.
INFO: 2014-Oct-03 13:46:22: Parameter freq for dump plane_test_vel is set to 1000.
INFO: 2014-Oct-03 13:46:22: Parameter header for dump plane_test_vel is set to .
INFO: 2014-Oct-03 13:46:22: Parameter scale for dump plane_test_vel is set to 0.1.
INFO: 2014-Oct-03 13:46:22: Parameter start for dump plane_test_vel is set to 0.
INFO: 2014-Oct-03 13:46:22: Parameter type for dump plane_test_vel is set to xyzv.
INFO: 2014-Oct-03 13:46:22: Parameter velocity for dump plane_test_vel is set to .
INFO: 2014-Oct-03 13:46:22: Dump type set to full
INFO: 2014-Oct-03 13:46:22: Dump will be sent to the file with base name plane_test with extension dat.
INFO: 2014-Oct-03 13:46:22: Dumping will start after 0 time steps.
INFO: 2014-Oct-03 13:46:22: Dump will be produced every 10000 time steps.
INFO: 2014-Oct-03 13:46:22: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2014-Oct-03 13:46:22: Include info header into the dump file.
INFO: 2014-Oct-03 13:46:22: Adding dump to file plane_test.
INFO: 2014-Oct-03 13:46:22: Parameter coordinate for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter director for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter freq for dump plane_test is set to 10000.
INFO: 2014-Oct-03 13:46:22: Parameter header for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter id for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter multi for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter radius for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter start for dump plane_test is set to 0.
INFO: 2014-Oct-03 13:46:22: Parameter tp for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Parameter type for dump plane_test is set to full.
INFO: 2014-Oct-03 13:46:22: Parameter velocity for dump plane_test is set to .
INFO: 2014-Oct-03 13:46:22: Planar constraint. Setting plane dimensions to lx = 100 and ly = 100.
INFO: 2014-Oct-03 13:46:22: Adding constraint of type plane.
INFO: 2014-Oct-03 13:46:22: Parameter lx for constraint plane is set to 100.
INFO: 2014-Oct-03 13:46:22: Parameter ly for constraint plane is set to 100.
INFO: 2014-Oct-03 13:46:22: Global first potential depth (A) for Gaussian pair potential is set to 2.0.
INFO: 2014-Oct-03 13:46:22: Global second potential depth (B) for Gaussian pair potential is set to -1.0.
WARNING: 2014-Oct-03 13:46:22: No first potential width (alpha) specified for the Gaussian pair potential. Setting it to 1.
WARNING: 2014-Oct-03 13:46:22: No second potential width (beta) specified for the Gaussian pair potential. Setting it to 3.
WARNING: 2014-Oct-03 13:46:22: No first potential peak position (rA) specified for the Gaussian pair potential. Setting it to 0.
WARNING: 2014-Oct-03 13:46:22: No second potential peak position (rB) specified for the Gaussian pair potential. Setting it to 1.5.
WARNING: 2014-Oct-03 13:46:22: No cutoff distance (rcut) specified for the Gaussian pair potential. Setting it to 3.0.
WARNING: 2014-Oct-03 13:46:22: Neighbour list cutoff distance (2.3999999999999999 is smaller than the Gaussian cuttof distance (3). Results will not be reliable.
INFO: 2014-Oct-03 13:46:22: Added pair potential : gaussian to the list of pair interactions.
INFO: 2014-Oct-03 13:46:22: Pair potential gaussian has neighbour list. Neighbour list updates will be performed during the simulation.
INFO: 2014-Oct-03 13:46:22: Added gaussian to the list of pair potentials.
INFO: 2014-Oct-03 13:46:22: Parameter A for pair potential gaussian is set to 2.0.
INFO: 2014-Oct-03 13:46:22: Parameter B for pair potential gaussian is set to -1.0.
INFO: 2014-Oct-03 13:46:22: Added logger. Logged quantities will be sent to plane_test.log.
INFO: 2014-Oct-03 13:46:22: Logs will be produced every 1000 time steps.
INFO: 2014-Oct-03 13:46:22: Adding log quantity : gaussian_energy.
INFO: 2014-Oct-03 13:46:22: Adding log quantity : velocity.
INFO: 2014-Oct-03 13:46:22: Adding logger to file plane_test.log.
WARNING: 2014-Oct-03 13:46:22: No group has been set. Assuming group 'all'.
WARNING: 2014-Oct-03 13:46:22: NVE integrator has limit on the maximum particle displacement. It is set to 0.0001.
INFO: 2014-Oct-03 13:46:22: Adding integrator of type nve.
INFO: 2014-Oct-03 13:46:22: Parameter dt for integrator nve is set to 0.001.
INFO: 2014-Oct-03 13:46:22: Parameter limit for integrator nve is set to 0.0001.
INFO: 2014-Oct-03 13:46:22: Starting simulation run for 10000 steps.
INFO: 2014-Oct-03 13:46:52: Built neighbour list 31 time. Average number of steps between two builds : 322.58064516129031.
INFO: 2014-Oct-03 13:46:52: Disabling integrator nve_all.
INFO: 2014-Oct-03 13:46:52: Adding particle by group g.
INFO: 2014-Oct-03 13:46:52: Added 81 particles to group g.
INFO: 2014-Oct-03 13:46:52: Adding group g.
WARNING: 2014-Oct-03 13:46:52: No group has been set. Assuming group 'all'.
INFO: 2014-Oct-03 13:46:52: Brownian dynamics integrator. Setting magnitude of active velocity to 0.5.
INFO: 2014-Oct-03 13:46:52: Brownian dynamics integrator. Setting rotational diffusion rate to 0.8.
INFO: 2014-Oct-03 13:46:52: Brownian dynamics integrator. Setting mobility to 1.0.
INFO: 2014-Oct-03 13:46:52: Brownian dynamics integrator. Setting random number generator seed to 1.
WARNING: 2014-Oct-03 13:46:52: Brownian dynamics integrator. Assuming polar order parameter.
INFO: 2014-Oct-03 13:46:52: Adding integrator of type brownian.
INFO: 2014-Oct-03 13:46:52: Parameter dt for integrator brownian is set to 0.001.
INFO: 2014-Oct-03 13:46:52: Parameter mu for integrator brownian is set to 1.0.
INFO: 2014-Oct-03 13:46:52: Parameter nu for integrator brownian is set to 0.8.
INFO: 2014-Oct-03 13:46:52: Parameter seed for integrator brownian is set to 1.
INFO: 2014-Oct-03 13:46:52: Parameter v0 for integrator brownian is set to 0.5.
INFO: 2014-Oct-03 13:46:52: Population. Applying population to group g.
INFO: 2014-Oct-03 13:46:52: Population. Population control frequency set to 1000.
WARNING: 2014-Oct-03 13:46:52: Random population control. No random number generator seed specified. Using default 0.
INFO: 2014-Oct-03 13:46:52: Random population control. Setting division rate 1000.0.
INFO: 2014-Oct-03 13:46:52: Random population control. Setting death rate 1000.0.
INFO: 2014-Oct-03 13:46:52: Adding population of type random.
INFO: 2014-Oct-03 13:46:52: Parameter death_rate for population random is set to 1000.0.
INFO: 2014-Oct-03 13:46:52: Parameter division_rate for population random is set to 1000.0.
INFO: 2014-Oct-03 13:46:52: Parameter freq for population random is set to 1000.
INFO: 2014-Oct-03 13:46:52: Parameter group for population random is set to g.
INFO: 2014-Oct-03 13:46:52: Starting simulation run for 100000 steps.
